server:
  port: 8011

spring:
  application:
    name: bff
#  main:
#    allow-bean-definition-overriding: true

logging:
  level:
    web: DEBUG
    org:
      springframework:
        web: DEBUG
        http: DEBUG
        graphql: DEBUG
      security: DEBUG
    reactor:
      netty: debug


app:
  token:
    secret: RANDOM_SECRET_FOR_JWT
    issuer: users-service
    expires-minute: 480