server:
  port: 8011

spring:
  application:
    name: bff

logging:
  level:
    web: DEBUG
    org:
      springframework:
        web: DEBUG
        http: DEBUG
        graphql: DEBUG
      security: DEBUG
    reactor:
      netty: debug